//! Mock AI cleanup provider for Spiel Phase 7.
//!
//! Simulates what a future AI-powered cleanup provider might do.
//! All output is clearly labeled as mock. No real AI, no network.
//!
//! This provider exists for testing the cleanup pipeline and UI
//! before real AI providers are implemented in future phases.

use crate::cleanup::{
    CleanupError, CleanupProvider, CleanupProviderKind, CleanupRequest, CleanupResult,
};
use crate::modes::TextModeKind;

/// Mock AI cleanup provider — simulates future AI behavior for testing.
/// All output is clearly labeled as mock-generated.
pub struct MockAiCleanupProvider;

impl CleanupProvider for MockAiCleanupProvider {
    fn cleanup(&self, request: &CleanupRequest) -> Result<CleanupResult, CleanupError> {
        let started_at = std::time::Instant::now();

        // Validate input
        let raw_trimmed = request.raw_text.trim().to_string();
        if raw_trimmed.is_empty() {
            return Err(CleanupError {
                code: "empty_raw_text".into(),
                message: "Cannot clean up empty text. Provide a transcript first.".into(),
                recoverable: true,
                details: None,
            });
        }

        // Simulate "AI" processing delay (very short, just for realism)
        std::thread::sleep(std::time::Duration::from_millis(150));

        // Apply mode-specific mock transformation
        let (final_text, warnings) = match request.mode {
            TextModeKind::RawDictation => mock_raw_dictation(&raw_trimmed),
            TextModeKind::CleanNotes => mock_clean_notes(&raw_trimmed),
            TextModeKind::AiPrompt => mock_ai_prompt(&raw_trimmed),
            TextModeKind::DeveloperReview => mock_developer_review(&raw_trimmed),
            TextModeKind::ThoughtPiece => mock_thought_piece(&raw_trimmed),
        };

        let duration_ms = started_at.elapsed().as_millis() as u64;
        let changed = final_text != raw_trimmed;

        let completed_at = crate::chrono_now_iso();

        Ok(CleanupResult {
            raw_text: raw_trimmed,
            final_text,
            mode: request.mode.clone(),
            provider: CleanupProviderKind::MockAi,
            is_mock: true,
            changed,
            created_at: request.created_at.clone(),
            completed_at,
            duration_ms,
            warnings,
            error: None,
        })
    }

    fn name(&self) -> &str {
        "Mock AI Cleanup"
    }

    fn kind(&self) -> CleanupProviderKind {
        CleanupProviderKind::MockAi
    }

    fn is_mock(&self) -> bool {
        true
    }
}

// ── Mock mode-specific functions ────────────────────────────

fn mock_header() -> String {
    "\n\n---\n[MOCK AI OUTPUT — This is not real AI cleanup. OpenAI and local LLM providers are planned for future phases.]\n".into()
}

fn mock_raw_dictation(text: &str) -> (String, Vec<String>) {
    let warnings = vec![
        "Mock AI provider. This is not real AI cleanup — for testing only.".into(),
        "OpenAI and local LLM providers are planned for future phases.".into(),
    ];
    let cleaned = format!("{}{}", text.trim(), mock_header());
    (cleaned, warnings)
}

fn mock_clean_notes(text: &str) -> (String, Vec<String>) {
    let warnings = vec![
        "Mock AI provider. The output simulates what future AI cleanup might look like.".into(),
        "This is not real AI. Review output carefully before using.".into(),
    ];

    // Simulate slightly smarter cleanup: remove common filler words
    let filler_patterns = ["um,", "Um,", "uh,", "Uh,", "you know,", "like,"];
    let mut cleaned = text.to_string();
    for pattern in &filler_patterns {
        cleaned = cleaned.replace(pattern, "");
    }

    let cleaned = cleaned.trim().to_string();
    let cleaned = format!(
        "[Mock AI Clean Notes — simulated cleanup]\n\n{}{}",
        cleaned,
        mock_header()
    );

    (cleaned, warnings)
}

fn mock_ai_prompt(text: &str) -> (String, Vec<String>) {
    let warnings =
        vec!["Mock AI provider. This prompt template was generated by a mock, not real AI.".into()];

    let final_text = format!(
        "[Mock AI Prompt — simulated AI prompt preparation]\n\nUse the following spoken notes as context and provide a thoughtful response.\n\nNotes:\n---\n{}\n---\n\n[Mock note: Real AI prompt optimization is planned for a future phase.]\n{}",
        text.trim(),
        mock_header()
    );

    (final_text, warnings)
}

fn mock_developer_review(text: &str) -> (String, Vec<String>) {
    let warnings = vec![
        "Mock AI provider. The review structure below was generated by a mock, not real AI.".into(),
    ];

    let final_text = format!(
        "[Mock AI Developer Review — simulated review generation]\n\n## Issue\n{}\n\n## Why It Matters\n(Mock analysis would appear here with real AI)\n\n## Suggested Fix\n(Mock suggestion would appear here with real AI)\n\n## Acceptance Criteria\n- [ ] (Mock criteria would appear here with real AI)\n\n## Raw Notes\n{}{}",
        text.trim(),
        text.trim(),
        mock_header()
    );

    (final_text, warnings)
}

fn mock_thought_piece(text: &str) -> (String, Vec<String>) {
    let warnings = vec![
        "Mock AI provider. The essay structure below was generated by a mock, not real AI.".into(),
    ];

    let final_text = format!(
        "[Mock AI Thought Piece — simulated essay structure]\n\n## Working Title\n(Mock title suggestion would appear here with real AI)\n\n## Core Idea\n{}\n\n## Raw Notes\n{}\n\n## Possible Sections\n- (Mock section suggestions would appear here with real AI)\n- \n- \n{}",
        text.trim(),
        text.trim(),
        mock_header()
    );

    (final_text, warnings)
}
